/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#006e2d",
        "primary-container": "#00873a",
        "on-surface": "#171d16",
        "on-error": "#ffffff",
        "outline-variant": "#bdcaba",
        "on-secondary-fixed": "#00210a",
        "primary-fixed": "#7ffc97",
        "error-container": "#ffdad6",
        "surface-container": "#e9f0e5",
        "error": "#ba1a1a",
        "primary": "#006b2c",
        "secondary-fixed": "#95f8a7",
        "surface-container-low": "#eff6ea",
        "secondary-container": "#92f5a4",
        "on-tertiary-fixed-variant": "#314d3e",
        "on-tertiary-fixed": "#042014",
        "background": "#f4fcf0",
        "on-tertiary": "#ffffff",
        "outline": "#6e7b6c",
        "tertiary-fixed-dim": "#afceba",
        "on-tertiary-container": "#f6fff6",
        "surface": "#f4fcf0",
        "secondary": "#006d30",
        "on-primary-fixed-variant": "#005320",
        "on-primary-fixed": "#002109",
        "on-secondary-container": "#007233",
        "surface-dim": "#d5dcd1",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2b322b",
        "tertiary": "#466252",
        "on-error-container": "#93000a",
        "on-background": "#171d16",
        "on-surface-variant": "#3e4a3d",
        "surface-container-highest": "#dde5d9",
        "surface-container-high": "#e3eadf",
        "on-secondary-fixed-variant": "#005323",
        "surface-variant": "#dde5d9",
        "on-secondary": "#ffffff",
        "inverse-primary": "#62df7d",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#62df7d",
        "tertiary-container": "#5e7b6a",
        "secondary-fixed-dim": "#79db8d",
        "tertiary-fixed": "#caead6",
        "on-primary-container": "#f7fff2",
        "inverse-on-surface": "#ecf3e7",
        "surface-bright": "#f4fcf0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "card": "18px",
        "input": "12px",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "12px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "base": "8px",
        "gutter": "16px"
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '"Inter"', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
